version: "3" 
services:
  react:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      -  /home/ret/node_modules
      - ./:/home/ret
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      -  /home/ret/node_modules
      - ./:/home/ret
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "test"]