FROM node:alpine

RUN cd home \
    && mkdir ret

RUN chmod -R 777 /home/ret

WORKDIR  /home/ret

COPY package.json ./

RUN npm install

# COPY ./ ./

CMD ["npm", "run", "start"]

ENV CHOKIDAR_USEPOLLING=true
